#!/bin/bash

# Copyright (c) OTH Regensburg, 2016
#
# Author:
#   Ralf Ramsauer <ralf.ramsauer@othr.de>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.

PATH=$PATH:../common/bin

function die {
  echo "$@" 1>&2;
  exit -1;
}

if [ -z "$1" ]
then
	projects=$(find -mindepth 1 -maxdepth 1 -type d)
else
	projects=$1
fi

for project in $projects
do
	cd $project
	git submodule update --init repo || die "submodule update failed"
	prepare_project ${project}.cfg || die "prepare_project failed for: $project"
	cd ..
done
