#!/bin/bash

# Copyright (c) OTH Regensburg, 2016
#
# Author:
#   Ralf Ramsauer <ralf.ramsauer@othr.de>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.

PATH=$PATH:../common/bin

function die {
  echo "$@" 1>&2;
  exit -1;
}

if [ -z "$1" ]
then
	projects=("busybox" "PreemptRT")
	git submodule update --init || die "Submodule init failed"
else
	projects=$1
fi

for project in "${projects[@]}"
do
	cd $project 2>/dev/null || die "Unknown project: $project"
	prepare_project ${project}.cfg || \
		die "prepare_project failed for: $project"
	cd ..
done
